#!/usr/bin/env python3
# -*- coding: utf-8 -*-

studens1 = [
    {'edad': 11, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 14, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'M'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'M'},
    {'edad': 8, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 7, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
]
studens2 = [
    {'edad': 11, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 14, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'M'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'M'},
    {'edad': 8, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 7, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
]

studens3 = [
    {'edad': 11, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 14, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'M'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'M'},
    {'edad': 8, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 7, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
]

studens4 = [
    {'edad': 11, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 14, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'M'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'M'},
    {'edad': 8, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 7, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
]

studens5 = [
    {'edad': 11, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 14, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'M'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'M'},
    {'edad': 8, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 7, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
]
studens6 = [
    {'edad': 11, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 14, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'M'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 11, 'sexo': 'F'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 10, 'sexo': 'M'},
    {'edad': 8, 'sexo': 'M'},
    {'edad': 12, 'sexo': 'F'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 9, 'sexo': 'M'},
    {'edad': 16, 'sexo': 'M'},
    {'edad': 15, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 7, 'sexo': 'F'},
    {'edad': 10, 'sexo': 'F'},
    {'edad': 13, 'sexo': 'F'},
    {'edad': 12, 'sexo': 'M'},
    {'edad': 11, 'sexo': 'F'},
]

school = [
    {'name_class': '1A', 'members': studens1, },
    {'name_class': '2A', 'members': studens2, },
    {'name_class': '3A', 'members': studens3, },
    {'name_class': '4A', 'members': studens4, },
    {'name_class': '5A', 'members': studens5, },
    {'name_class': '6A', 'members': studens6, },
]


